### ISSUE TITLE
Multiple markdown replacements on same line don't work

### ISSUE THREAD

**Issue by sachinrekhi** [morishjs/quill-markdown-toolbar#10]
If you have a markdown line like the following:

* **Test**: more text
This should be changed into a list item and then bolded text.

The list item is created but the bolded text is not.

I seem to have found the error in this line:

```
lineText = this.quill.getText(this.quill.getIndex(line), lineText.length);
```

This does not pick up the rest of the line after the the list item substitution is made. Any way to get it to correctly pick up the rest of the lineText so it can continue with further substitutions?

Thanks a lot for any insights!

**Comment by sachinrekhi** [comment]
I was able to fix this by rewriting the lines for loop to the following:

```
lines.forEach((line, index) => {
            let lineText = line.domNode.textContent
            let lineIndex = this.quill.getIndex(line)
            let oldLineText = null

            while (oldLineText !== lineText) {
                oldLineText = lineText

                for (let match of this.matches) {
                    const matchedText = lineText.match(match.pattern)

                    if (matchedText) {
                        // NOTE: `code-block` is special (multi-line)
                        if (match.name === 'code-block') {
                            if (index + 1 === lines.length - 1) {
                                continue
                            }

                            const restOfLines = lines.slice(index + 1, lines.length)
                            const lastIndex = restOfLines.findIndex(l => l.domNode.textContent.match(match.pattern))
                            if (lastIndex === -1) {
                                continue
                            }

                            match.action(this.quill.getIndex(line), this.quill.getIndex(restOfLines[lastIndex]))
                            lines.splice(index, lastIndex + 1)

                            break
                        } else {
                            match.action(lineText, match.pattern, lineIndex)

                            let updatedLine = this.quill.getLine(lineIndex)[0]
                            lineText = updatedLine.domNode.textContent
                            
                            break
                        }
                    }
                }
            }
        })
```

**Comment by morishjs** [comment]
@sachinrekhi 
Thank you for reporting a bug with a great solution.
I will check in detail and fix it as soon as possible.

Sorry for inconvenience :(

**Comment by sachinrekhi** [comment]
@morishjs By the way, do you know why the following line appears in a lot of the matchers? I don't quite get what this is specifically avoiding?

```
if (text.match(/^([*_ \n]+)$/g)) return;
```

**Comment by morishjs** [comment]
@sachinrekhi 
For a `bold` formatting case, the following string will be converted to an empty string and then turning on bold formatting.

```
** ** => (empty string)
```

I am seriously considering removing it because I can't give anyone else compelling reason.

**Comment by sachinrekhi** [comment]
Got it! Thanks for the explanation.

**Comment by morishjs** [comment]
@sachinrekhi 
Thank you for contributing to this repository. I've fixed the error, so please make sure the program works as you expected.
Updated version is v0.1.3.
