### ISSUE TITLE
Code blocks with multiple lines do not work

### ISSUE THREAD

**Issue by ada-anil** [morishjs/quill-markdown-toolbar#5]
If there is a code block (specified with triple backticks) spanning multiple lines, only the first line of the code is styled.

**Comment by morishjs** [comment]
@ada-anil 
Sorry for the inconvenience, I hadn't refactored, corrected some bugs recently because of a busy schedule in the workplace.

I probably try to fix the bug next week. 

Thank you for opening the first issue :)

**Comment by ada-anil** [comment]
Thanks. I'll try it out this weekend.

**Comment by ada-anil** [comment]
I have a minor comment:

In github, if you do something like:

[triple-quotes]def f(x):
return x
[triple-quotes]

`def f(x):` gets removed and all you see is `return x`.

With the quill markdown, the above produces:

```
ef f(x):
    return x
```

So it seems to remove the first letter `d`. Personally I would prefer if it just worked properly (so I am not sure why github removes the whole first line).

This is not a big issue, but I thought you should know.

**Comment by morishjs** [comment]
@ada-anil 
Thank you for detailed feedback.
I would consider reflecting on your comment next version.
